--  10. Revenue Analysis
-- ● Assume the following monthly subscription prices, calculate the total revenue
-- generated by both platforms (LioCinema and Jotstar) for the analysis period (January
-- to November 2024).

-- LIOCINEMA	Basic -> 69		Premium -> 129
-- JOTSTAR		Premium -> 359	VIP -> 159

-- The calculation should consider:
-- ❖ Subscribers count under each plan.
-- ❖ Active duration of subscribers on their respective plans.
-- ❖ Upgrades and downgrades during the period, ensuring revenue reflects the
-- time spent under each plan.


(WITH CTE AS (SELECT *
 FROM liocinema_db.subscribers
WHERE (subscription_date <= "2024-11-30" OR plan_change_date <= "2024-11-30")
AND (subscription_date >= "2024-01-01" OR plan_change_date >= "2024-01-01")
AND (subscription_plan IN ("Basic","Premium") OR new_subscription_plan IN ("Basic","Premium"))),

CTE2 AS(SELECT user_id, subscription_date AS subscription_start_date, subscription_plan,LEAST(
    COALESCE(last_active_date, '2024-11-30'),
    COALESCE(plan_change_date, '2024-11-30'),
    '2024-11-30') AS subscription_end_date,
TIMESTAMPDIFF(MONTH, subscription_date, LEAST(
    COALESCE(last_active_date, '2024-11-30'),
    COALESCE(plan_change_date, '2024-11-30'),
    '2024-11-30')) AS no_of_months
 FROM CTE WHERE subscription_date <= "2024-11-30" AND subscription_date >= "2024-01-01"
 UNION ALL
 SELECT user_id, plan_change_date AS subscription_start_date, new_subscription_plan,"2024-11-30" AS subscription_end_date,
 TIMESTAMPDIFF(MONTH, plan_change_date, "2024-11-30") AS no_of_months
 FROM CTE WHERE plan_change_date <= "2024-11-30" AND plan_change_date >= "2024-01-01")
 
 SELECT subscription_plan, 
 SUM(CASE WHEN subscription_plan = "Basic" THEN 69 * no_of_months
 WHEN subscription_plan = "Premium" THEN 129 * no_of_months END) AS revenue,  "Liocinema" as platform FROM CTE2
 WHERE subscription_plan IN ("Basic", "Premium")
 GROUP BY 1)
 
 union
 
 (WITH CTE AS (SELECT *
 FROM jotstar_db.subscribers
WHERE (subscription_date <= "2024-11-30" OR plan_change_date <= "2024-11-30")
AND (subscription_date >= "2024-01-01" OR plan_change_date >= "2024-01-01")
AND (subscription_plan IN ("Basic","Premium") OR new_subscription_plan IN ("VIP","Premium"))),

CTE2 AS(SELECT user_id, subscription_date AS subscription_start_date, subscription_plan,LEAST(
    COALESCE(last_active_date, '2024-11-30'),
    COALESCE(plan_change_date, '2024-11-30'),
    '2024-11-30') AS subscription_end_date,
TIMESTAMPDIFF(MONTH, subscription_date, LEAST(
    COALESCE(last_active_date, '2024-11-30'),
    COALESCE(plan_change_date, '2024-11-30'),
    '2024-11-30')) AS no_of_months
 FROM CTE WHERE subscription_date <= "2024-11-30" AND subscription_date >= "2024-01-01"
 UNION ALL
 SELECT user_id, plan_change_date AS subscription_start_date, new_subscription_plan,"2024-11-30" AS subscription_end_date,
 TIMESTAMPDIFF(MONTH, plan_change_date, "2024-11-30") AS no_of_months
 FROM CTE WHERE plan_change_date <= "2024-11-30" AND plan_change_date >= "2024-01-01")
 
 SELECT subscription_plan, 
 SUM(CASE WHEN subscription_plan = "VIP" THEN 159 * no_of_months
 WHEN subscription_plan = "Premium" THEN 359 * no_of_months END) AS revenue,  "Jotstar" as platform FROM CTE2
 WHERE subscription_plan IN ("VIP", "Premium")
 GROUP BY 1);